### ISSUE TITLE
Deployment: Vercel deployment for each app

### ISSUE THREAD

**Issue by gksander** [FormidableLabs/showcase-nextjs-zones#4]
## What?

Deploy each of the three NextJS apps to Vercel. Vercel [has a post](https://vercel.com/blog/monorepos) about deploying from monorepos, so we should be able to follow along with that. See [this demo](https://github.com/vercel/next.js/tree/canary/examples/with-zones) also for some more details on importing projects into Vercel.

**Comment by jebadirad** [comment]
@upatel32  i believe this is closed ya?

**Comment by upatel32** [comment]
yes!
